version: "3.2"
services:
    nodejs:
        build:
            context: .
        image: amakundu/nodejs-mysql-app
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_HOST=mysql-app
            - MYSQL_USER=admin
            - MYSQL_PASS=admin
            - MYSQL_DB=apiemployees
        ports:
            - "4000:4000"
        container_name: nodejs-app
    mysql:
        image: mysql:5.7
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=456
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=apiemployees
        container_name: mysql-app
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        depends_on:
            - mysql
        networks:
            - backend
        ports:
            - "3000:80"
        environment:
            - PMA_HOST=mysql-app
            - PMA_PORT= 3306
        container_name: phpmyadmin-app
networks:
    frontend:
    backend: